### ISSUE TITLE
I am unable to get the conversion to django model to work

### ISSUE THREAD

**Issue by TMda** [josemlp91/staruml-django#1]
hello  @josemlp91 , I  downloaded the basic type installed the extension, but i am unable to get the conversion to correct django model type to work .

this an example of model class that i get:
```
from django.db import models

class Purchase_Order(models.Model):
    class Meta:
        pass

    ID String = None
    Supplier String = None
    Date_Issued Date = None
    Attribute1 = None
```

```

**Comment by josemlp91** [comment]
Extension is not finding the suitable type to match with Django models fields. I can know if the problem is caused by your particular way to import the "basic types" or other issue.

It's important use the field **type** (editor > properties) dialog. 

![](http://pix.toile-libre.org/upload/original/1533568677.png)

If the problem continue, I would like see your diagram. 
Thank you very much.

**Comment by TMda** [comment]
Thank you Jose Miguel,

I saw what you meant, it works now.

Kind regards
Thomas
